services:
  - type: web
    name: carparking          # Your service name (can be homesecurity if that's the folder name)
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn carparking.wsgi:application

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
